/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from "react";
import { 
  ShoppingBag, Sparkles, Plus, Search, Tag, DollarSign, Package, 
  Layers, Check, CheckCircle2, Truck, XCircle, Clock, Trash 
} from "lucide-react";
import { Product, Order } from "../types.js";

interface CatalogProps {
  products: Product[];
  orders: Order[];
  onAddProduct: (product: Omit<Product, "id">) => Promise<any>;
  onUpdateOrderStatus: (id: string, status: Order["status"], paymentStatus?: Order["paymentStatus"]) => Promise<any>;
}

export default function Catalog({ products, orders, onAddProduct, onUpdateOrderStatus }: CatalogProps) {
  const [activeTab, setActiveTab] = useState<"products" | "orders">("products");
  
  // Search states
  const [prodSearch, setProdSearch] = useState("");
  const [orderSearch, setOrderSearch] = useState("");
  const [orderStatusFilter, setOrderStatusFilter] = useState("all");

  // Add Product modal state
  const [showAddProductModal, setShowAddProductModal] = useState(false);
  const [newProdName, setNewProdName] = useState("");
  const [newProdPrice, setNewProdPrice] = useState(2000);
  const [newProdStock, setNewProdStock] = useState(50);
  const [newProdSku, setNewProdSku] = useState("");
  const [newProdImage, setNewProdImage] = useState("");
  const [newProdDesc, setNewProdDesc] = useState("");

  const handleAddProductSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newProdName.trim()) return;

    await onAddProduct({
      name: newProdName,
      price: Number(newProdPrice),
      stock: Number(newProdStock),
      sku: newProdSku || `AURA-M-${Date.now().toString().slice(-4)}`,
      image: newProdImage || "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=400&q=80",
      description: newProdDesc
    });

    // Reset fields
    setNewProdName("");
    setNewProdPrice(2000);
    setNewProdStock(50);
    setNewProdSku("");
    setNewProdImage("");
    setNewProdDesc("");
    setShowAddProductModal(false);
  };

  const handleStatusChange = async (orderId: string, status: Order["status"], payment?: Order["paymentStatus"]) => {
    await onUpdateOrderStatus(orderId, status, payment);
  };

  // Filters
  const filteredProducts = products.filter(p => 
    (p.name || '').toLowerCase().includes((prodSearch || '').toLowerCase()) ||
    (p.sku || '').toLowerCase().includes((prodSearch || '').toLowerCase())
  );

  const filteredOrders = orders.filter(o => {
    const matchesSearch = 
      (o.customerName || '').toLowerCase().includes((orderSearch || '').toLowerCase()) ||
      (o.id || '').toLowerCase().includes((orderSearch || '').toLowerCase());
    
    const matchesStatus = orderStatusFilter === "all" || o.status === orderStatusFilter;

    return matchesSearch && matchesStatus;
  });

  return (
    <div className="space-y-6">
      {/* Upper bar */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between pb-2 border-b border-gray-100 gap-3">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight text-gray-900">E-Commerce Center</h1>
          <p className="text-sm text-gray-500">Track and manage products, inventories, and incoming orders generated by AI.</p>
        </div>

        {/* Tab switchers */}
        <div className="flex bg-gray-100 rounded-xl p-1 text-xs font-semibold self-start sm:self-center">
          <button
            onClick={() => setActiveTab("products")}
            className={`px-4 py-2 rounded-lg transition-colors flex items-center gap-1.5 ${activeTab === "products" ? "bg-white text-gray-900 shadow-xs" : "text-gray-500 hover:text-gray-900"}`}
          >
            <Package className="w-4 h-4" />
            Product Catalog ({products.length})
          </button>
          <button
            onClick={() => setActiveTab("orders")}
            className={`px-4 py-2 rounded-lg transition-colors flex items-center gap-1.5 ${activeTab === "orders" ? "bg-white text-gray-900 shadow-xs" : "text-gray-500 hover:text-gray-900"}`}
          >
            <ShoppingBag className="w-4 h-4" />
            Incoming Orders ({orders.length})
          </button>
        </div>
      </div>

      {/* PRODUCTS VIEW */}
      {activeTab === "products" && (
        <div className="space-y-4">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-3">
            <div className="relative w-full sm:w-80">
              <Search className="absolute left-3 top-2.5 w-4 h-4 text-gray-400" />
              <input
                type="text"
                placeholder="Search products by title, SKU..."
                value={prodSearch}
                onChange={(e) => setProdSearch(e.target.value)}
                className="w-full pl-9 pr-3 py-1.5 text-xs bg-white border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-indigo-500"
              />
            </div>
            
            <button
              onClick={() => setShowAddProductModal(true)}
              className="w-full sm:w-auto inline-flex items-center gap-2 px-4 py-2 bg-gray-900 hover:bg-gray-800 text-white rounded-xl shadow-sm text-xs font-semibold transition-colors"
            >
              <Plus className="w-4 h-4" />
              Add Product
            </button>
          </div>

          {/* Product Grid */}
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 text-left">
            {filteredProducts.map(prod => (
              <div key={prod.id} className="bg-white border border-gray-100 rounded-2xl overflow-hidden shadow-2xs hover:shadow-md transition-shadow flex flex-col justify-between">
                <div>
                  <div className="aspect-square w-full relative bg-gray-100">
                    <img src={prod.image} alt={prod.name} className="w-full h-full object-cover" />
                    <span className="absolute top-2.5 left-2.5 bg-gray-900/85 backdrop-blur-xs text-white text-[9px] font-bold tracking-wider uppercase px-2 py-0.5 rounded-md">
                      {prod.sku}
                    </span>
                  </div>
                  
                  <div className="p-4 space-y-1.5">
                    <h3 className="text-xs font-semibold text-gray-900 truncate">{prod.name}</h3>
                    <p className="text-[11px] text-gray-400 leading-normal line-clamp-2 h-8 font-normal">
                      {prod.description}
                    </p>
                  </div>
                </div>

                <div className="p-4 pt-0 border-t border-gray-50 flex items-center justify-between mt-3">
                  <div className="text-left">
                    <p className="text-[9px] font-bold text-gray-400 uppercase tracking-wider">Price</p>
                    <p className="text-xs font-bold text-indigo-600">{prod.price} BDT</p>
                  </div>
                  <div className="text-right">
                    <p className="text-[9px] font-bold text-gray-400 uppercase tracking-wider">Stock</p>
                    <span className={`text-xs font-bold ${prod.stock < 20 ? "text-red-500 animate-pulse" : "text-gray-700"}`}>
                      {prod.stock} items
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ORDERS VIEW */}
      {activeTab === "orders" && (
        <div className="space-y-4">
          <div className="flex flex-col sm:flex-row gap-3 items-center justify-between">
            <div className="relative w-full sm:w-80">
              <Search className="absolute left-3 top-2.5 w-4 h-4 text-gray-400" />
              <input
                type="text"
                placeholder="Search orders by customer or ID..."
                value={orderSearch}
                onChange={(e) => setOrderSearch(e.target.value)}
                className="w-full pl-9 pr-3 py-1.5 text-xs bg-white border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-indigo-500"
              />
            </div>

            <select
              value={orderStatusFilter}
              onChange={(e) => setOrderStatusFilter(e.target.value)}
              className="w-full sm:w-44 px-2.5 py-1.5 text-xs bg-white border border-gray-200 rounded-lg"
            >
              <option value="all">All Statuses</option>
              <option value="pending">Pending Approval</option>
              <option value="processing">Processing</option>
              <option value="shipped">Shipped</option>
              <option value="delivered">Delivered</option>
              <option value="cancelled">Cancelled</option>
            </select>
          </div>

          {/* Orders Table */}
          <div className="bg-white border border-gray-100 rounded-2xl overflow-hidden shadow-2xs text-left">
            <div className="overflow-x-auto">
              <table className="w-full text-xs">
                <thead>
                  <tr className="bg-gray-50 text-gray-500 uppercase tracking-wider font-semibold text-[10px] border-b border-gray-100">
                    <th className="px-6 py-3.5">Order ID</th>
                    <th className="px-6 py-3.5">Customer Name</th>
                    <th className="px-6 py-3.5">Purchased Items</th>
                    <th className="px-6 py-3.5">Total Amount</th>
                    <th className="px-6 py-3.5">Order Status</th>
                    <th className="px-6 py-3.5">Payment Method</th>
                    <th className="px-6 py-3.5">Date Created</th>
                    <th className="px-6 py-3.5 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {filteredOrders.length === 0 ? (
                    <tr>
                      <td colSpan={8} className="py-8 text-center text-gray-400">
                        No orders recorded matching criteria.
                      </td>
                    </tr>
                  ) : (
                    filteredOrders.map(ord => (
                      <tr key={ord.id} className="hover:bg-gray-50/50 transition-colors">
                        <td className="px-6 py-4 font-bold text-gray-900">
                          #{ord.id.split("-")[1] || "NEW"}
                        </td>
                        <td className="px-6 py-4 font-semibold text-gray-900">
                          {ord.customerName}
                        </td>
                        <td className="px-6 py-4 max-w-xs">
                          <p className="truncate font-normal text-gray-600">
                            {ord.items.map(i => `${i.productName} (x${i.quantity})`).join(", ")}
                          </p>
                        </td>
                        <td className="px-6 py-4 font-bold text-indigo-600">
                          {ord.totalAmount} BDT
                        </td>
                        <td className="px-6 py-4">
                          <span className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-semibold border ${
                            ord.status === "pending" ? "bg-amber-50 text-amber-700 border-amber-100" :
                            ord.status === "processing" ? "bg-indigo-50 text-indigo-700 border-indigo-100" :
                            ord.status === "shipped" ? "bg-blue-50 text-blue-700 border-blue-100" :
                            ord.status === "delivered" ? "bg-emerald-50 text-emerald-700 border-emerald-100" :
                            "bg-red-50 text-red-700 border-red-100"
                          }`}>
                            {ord.status === "pending" && <Clock className="w-3 h-3" />}
                            {ord.status === "processing" && <Package className="w-3 h-3" />}
                            {ord.status === "shipped" && <Truck className="w-3 h-3" />}
                            {ord.status === "delivered" && <CheckCircle2 className="w-3 h-3" />}
                            {ord.status === "cancelled" && <XCircle className="w-3 h-3" />}
                            <span className="capitalize">{ord.status}</span>
                          </span>
                        </td>
                        <td className="px-6 py-4 font-semibold text-gray-500 uppercase tracking-wider">
                          {ord.paymentStatus}
                        </td>
                        <td className="px-6 py-4 text-gray-400 font-medium">
                          {new Date(ord.createdAt).toLocaleDateString()}
                        </td>
                        <td className="px-6 py-4 text-right space-x-1 whitespace-nowrap">
                          {ord.status === "pending" && (
                            <button
                              onClick={() => handleStatusChange(ord.id, "processing")}
                              className="px-2 py-1 text-[10px] font-bold bg-indigo-50 hover:bg-indigo-100 text-indigo-700 border border-indigo-100 rounded-md shadow-3xs"
                            >
                              Approve
                            </button>
                          )}
                          {ord.status === "processing" && (
                            <button
                              onClick={() => handleStatusChange(ord.id, "shipped")}
                              className="px-2 py-1 text-[10px] font-bold bg-blue-50 hover:bg-blue-100 text-blue-700 border border-blue-100 rounded-md shadow-3xs"
                            >
                              Ship Order
                            </button>
                          )}
                          {ord.status === "shipped" && (
                            <button
                              onClick={() => handleStatusChange(ord.id, "delivered", "paid")}
                              className="px-2 py-1 text-[10px] font-bold bg-emerald-50 hover:bg-emerald-100 text-emerald-700 border border-emerald-100 rounded-md shadow-3xs"
                            >
                              Mark Delivered
                            </button>
                          )}
                          {ord.status !== "delivered" && ord.status !== "cancelled" && (
                            <button
                              onClick={() => handleStatusChange(ord.id, "cancelled")}
                              className="px-2 py-1 text-[10px] font-bold bg-red-50 hover:bg-red-100 text-red-700 border border-red-100 rounded-md shadow-3xs"
                            >
                              Cancel
                            </button>
                          )}
                          {(ord.status === "delivered" || ord.status === "cancelled") && (
                            <span className="text-[10px] text-gray-400 font-semibold italic">Archived</span>
                          )}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* Add Product Modal */}
      {showAddProductModal && (
        <div className="fixed inset-0 bg-black/55 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl w-full max-w-md p-6 shadow-2xl relative text-left space-y-4">
            <div className="flex items-center justify-between pb-2 border-b border-gray-100">
              <h3 className="font-bold text-gray-900 text-base">Introduce New Product Item</h3>
              <button onClick={() => setShowAddProductModal(false)} className="text-gray-400 hover:text-gray-900 font-bold text-lg">×</button>
            </div>

            <form onSubmit={handleAddProductSubmit} className="space-y-3.5 text-xs">
              <div>
                <label className="block font-semibold text-gray-600 mb-1">Product Name *</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Royal Cotton Panjabi"
                  value={newProdName}
                  onChange={(e) => setNewProdName(e.target.value)}
                  className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-semibold text-gray-600 mb-1">Price (BDT) *</label>
                  <input
                    type="number"
                    required
                    value={newProdPrice}
                    onChange={(e) => setNewProdPrice(Number(e.target.value))}
                    className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block font-semibold text-gray-600 mb-1">Initial Stock *</label>
                  <input
                    type="number"
                    required
                    value={newProdStock}
                    onChange={(e) => setNewProdStock(Number(e.target.value))}
                    className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-semibold text-gray-600 mb-1">SKU Code</label>
                  <input
                    type="text"
                    placeholder="e.g. AURA-P-02"
                    value={newProdSku}
                    onChange={(e) => setNewProdSku(e.target.value)}
                    className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block font-semibold text-gray-600 mb-1">Image URL</label>
                  <input
                    type="text"
                    placeholder="Image link..."
                    value={newProdImage}
                    onChange={(e) => setNewProdImage(e.target.value)}
                    className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none"
                  />
                </div>
              </div>

              <div>
                <label className="block font-semibold text-gray-600 mb-1">Description</label>
                <textarea
                  placeholder="Insert premium item specifications and details..."
                  value={newProdDesc}
                  onChange={(e) => setNewProdDesc(e.target.value)}
                  rows={2}
                  className="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none resize-none"
                />
              </div>

              <div className="pt-2 flex gap-3">
                <button
                  type="button"
                  onClick={() => setShowAddProductModal(false)}
                  className="w-1/2 py-2 border rounded-lg hover:bg-gray-50 font-semibold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="w-1/2 py-2 bg-gray-900 hover:bg-gray-800 text-white rounded-lg shadow-xs font-semibold"
                >
                  Save Product
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
